source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

target 'Broadcast' do
  pod "PerchBroadcast", :path => "../"
end

target 'BroadcastMock' do
  pod "PerchBroadcast", :path => "../"
end

target 'PerchBroadcastTests' do
  pod "PerchBroadcast", :path => "../"
  pod 'URLMock', '~> 1.3.1'
end
